title: João Victor Nóbrega # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Farmacêutico | Analista de Dados
  <br><br>
  Power BI | SQL
  <br><br>
  <a href="https://www.linkedin.com/in/jo%C3%A3o-victor-n%C3%B3brega-76547a3a/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-V4B2J74EHR # your Google Analytics tracking ID here
